openapi: 3.0.0
info:
  title: JWT Validator API
  description: API para validar tokens JWT. Recebe um token e retorna uma mensagem indicando se o token e valido ou nao.
  version: 1.0.0
servers:
  - url: http://endpoint-url/api
    description: Servidor local para desenvolvimento

paths:
  /validate:
    post:
      summary: Valida um token JWT
      description: Este endpoint valida um token JWT e retorna uma mensagem indicando se o token e valido ou nao.
      operationId: validateJwtToken
      requestBody:
        description: Token JWT a ser validado.
        content:
          application/text:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Token JWT a ser validado.
              required:
                - token
        required: true
      responses:
        '200':
          description: Token JWT e valido.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: JWT is valid
        '400':
          description: Requisicao invalida. O token pode estar ausente ou malformado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request: Token is missing or malformed"
        '500':
          description: Erro interno do servidor ao validar o token JWT.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred while validating the JWT token
      x-amazon-apigateway-integration:
        uri: http://my-nlb-873781d3a6e5989c.elb.sa-east-1.amazonaws.com/api/validate # DNS do NLB
        connectionType: VPC_LINK
        connectionId: cqf6tn  # ID do VPC Link
        httpMethod: POST
        type: http_proxy  # Tipo de integracao
        requestParameters:
          integration.request.header.Content-Type: "'application/text'"  # Se necessario
        responses:
          default:
            statusCode: '200'
components:
  schemas:
    TokenRequest:
      type: object
      properties:
        token:
          type: string
          description: Token JWT a ser validado.
      required:
        - token