apiVersion: apps/v1
kind: Deployment
metadata:
  nome: jwt-validator
spec:
  replicas:
  selector:
    matchLabels:
      app: jwt-validator
  template:
    metadata:
      labels:
        app: jwt-validator
    spec:
      containers:
        - name: jwt-validator
        image: 155314306528.dkr.ecr.sa-east-1.amazonaws.com/jwt-validator
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jwt-validator-service
spec:
  selector:
    app: jwt-validator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
